import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Intro from './intro';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className={`${inter.className} bg-[#313131] text-gray-950 relative dark:bg-[#100f0f] dark:text-[#d6d6d6] `}>
        <Intro />
       {children}
       </body>
    </html>
  );
}
